server:
  port: 8085

iamport:
  api:
    key: 0456330388304875
    secret: IRAFbtISOQAxccAf9pC9vsQKQEDL5JitgeQ8vtZL2qb6PpuZuU2Kz1x4E470XO1PVNCaAtPWLY904zLS

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates #file:src/main/resources/templates
    suffix: .html

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shoppingmall
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true